name = "PartitionedLS"
uuid = "19f41c5e-8610-11e9-2f2a-0d67e7c5027f"
authors = ["Roberto Esposito <roberto.esposito@unito.it>"]
version = "1.0.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.10"
DocStringExtensions = "0.9"
MLJModelInterface = "1"
NonNegLeastSquares = "0.4"
Tables = "1.0"
julia = "1.10"

[extras]
MLJTestInterface = "72560011-54dd-4dc2-94f3-c5de45b75ecd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"

[targets]
test = ["MLJTestInterface", "MLJBase", "MLJ", "Test"]



